create table
public."Activities" (
activity_id bigint generated by default as identity not null,
activity_title text not null,
activity_type text not null,
activity_description text not null,
activity_location text null,
activity_date date not null,
created_at timestamp with time zone not null default now(),
constraint Activities_pkey primary key (activity_id)
) tablespace pg_default;