create table
  public."ApplicationStatus" (
    application_status_id bigint generated by default as identity not null,
    job_application_id bigint null,
    date_applied date not null,
    date_initial_interview date null,
    description_initial_interview text null,
    date_exam date null,
    date_final date null,
    final_result text null,
    constraint ApplicationSTatus_pkey primary key (application_status_id),
    constraint ApplicationSTatus_job_application_id_fkey foreign key (job_application_id) references "JobApplications" (job_application_id) on update cascade on delete cascade
  ) tablespace pg_default;
