CREATE TABLE "GraduateTracerStudy" (
    id SERIAL PRIMARY KEY,
    alumni_id uuid NOT NULL,
    contact_numbers TEXT,
    civil_status TEXT,
    sex TEXT,
    region TEXT,
    province TEXT,
    location_of_residence TEXT,
    educational_background JSONB,
    professional_examination JSONB,
    course_reasons JSONB,
    training_after_college JSONB,
    advance_studies_reason TEXT,
    other_advance_studies_reason TEXT,
    employment_status TEXT,
    unemployment_reasons JSONB,
    other_unemployment_reason TEXT,
    present_employment_status TEXT,
    present_occupation TEXT,
    major_line_of_business TEXT,
    place_of_work TEXT,
    is_first_time_job_after_college TEXT,
    staying_on_job_reasons JSONB,
    other_staying_on_job_reason TEXT,
    is_first_job_related_to_course TEXT,
    first_job_related_to_course_reasons JSONB,
    other_first_job_related_to_course_reason TEXT,
    leaving_job_reasons JSONB,
    other_leaving_job_reason TEXT,
    staying_duration_in_first_job JSONB,
    other_staying_duration_in_first_job TEXT,
    first_job_found_through JSONB,
    other_first_job_found_through TEXT,
    duration_before_first_job JSONB,
    other_duration_before_first_job TEXT,
    job_levels JSONB,
    initial_gross_first_job TEXT,
    is_curriculum_relevant_in_first_job TEXT,
    learned_competencies JSONB,
    other_learned_competencies TEXT,
    suggestions TEXT,
    constraint GraduateTracerStudy_alumni_id_fkey foreign key (alumni_id) references auth.users (id) on update cascade on delete cascade
);