create table
  public."JobApplications" (
    job_application_id bigint generated by default as identity not null,
    job_posting_id bigint not null,
    applicant_id uuid not null,
    application_status text not null default 'pending'::text,
    application_date timestamp with time zone not null default now(),
    constraint JobApplications_pkey primary key (job_application_id),
    constraint JobApplications_applicant_id_fkey foreign key (applicant_id) references auth.users (id) on update cascade on delete cascade,
    constraint JobApplications_job_posting_id_fkey foreign key (job_posting_id) references "JobPostings" (job_posting_id) on update cascade on delete cascade
  ) tablespace pg_default;