create table
  public."JobPostings" (
    job_posting_id bigint generated by default as identity not null,
    agency_id uuid not null,
    job_title text not null,
    job_description text not null,
    job_location text not null,
    job_type text not null,
    salary_range text null,
    industry text null,
    application_deadline date not null,
    date_posted timestamp with time zone not null default now(),
    job_status text not null default 'pending'::text,
    constraint JobPostings_pkey primary key (job_posting_id),
    constraint JobPostings_agency_id_fkey foreign key (agency_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;