create table
  public."JobPostingEngagement" (
    engagement_id bigint generated by default as identity not null,
    job_posting_id bigint not null,
    view_count bigint not null,
    date_year date not null,
    constraint JobPostingEngagement_pkey primary key (engagement_id),
    constraint JobPostingEngagement_job_posting_id_fkey foreign key (job_posting_id) references "JobPostings" (job_posting_id) on update cascade on delete cascade
  ) tablespace pg_default;