create table
  "Notifications" (
    notification_id bigint generated by default as identity not null,
    receiver_id uuid not null,
    message text not null,
    seen boolean not null default false,
    created_at timestamp with time zone not null default now(),
    constraint Notifications_pkey primary key (notification_id),
    constraint Notifications_receiver_id_fkey foreign key (receiver_id) references auth.users (id) on update cascade on delete cascade
  ) tablespace pg_default;