CREATE VIEW "ViewGraduateTracerStudy" AS
SELECT 
  gts.id,
  gts.alumni_id,
  gts.contact_numbers,
  gts.civil_status,
  gts.sex,
  gts.region,
  gts.province,
  gts.location_of_residence,
  gts.educational_background,
  gts.professional_examination,
  gts.course_reasons,
  gts.training_after_college,
  gts.advance_studies_reason,
  gts.other_advance_studies_reason,
  gts.employment_status,
  gts.unemployment_reasons,
  gts.other_unemployment_reason,
  gts.present_employment_status,
  gts.present_occupation,
  gts.major_line_of_business,
  gts.place_of_work,
  gts.agency,
  gts.is_first_time_job_after_college,
  gts.staying_on_job_reasons,
  gts.other_staying_on_job_reason,
  gts.is_first_job_related_to_course,
  gts.first_job_related_to_course_reasons,
  gts.other_first_job_related_to_course_reason,
  gts.leaving_job_reasons,
  gts.other_leaving_job_reason,
  gts.staying_duration_in_first_job,
  gts.other_staying_duration_in_first_job,
  gts.first_job_found_through,
  gts.other_first_job_found_through,
  gts.duration_before_first_job,
  gts.other_duration_before_first_job,
  gts.job_levels,
  gts.initial_gross_first_job,
  gts.is_curriculum_relevant_in_first_job,
  gts.learned_competencies,
  gts.other_learned_competencies,
  gts.suggestions,
  u.created_at,
  u.raw_user_meta_data->>'first_name' as first_name,
  u.raw_user_meta_data->>'last_name' as last_name,
  u.raw_user_meta_data->>'middle_name' as middle_name,
  u.raw_user_meta_data->>'program' as program,
  u.raw_user_meta_data->>'college' as college,
  u.raw_user_meta_data->>'batch_year' as batch_year,
  u.raw_user_meta_data->>'gender' as gender
FROM 
  "GraduateTracerStudy" gts
JOIN 
  auth.users u ON gts.alumni_id = u.id;