export const mockJobApplications = [
  {
    job_application_id: 1,
    job_title: "Software Developer",
    applicant_name: "John Doe",
    application_date: "2024-09-01",
    application_status: "pending",
    action: "View",
  },
  {
    job_application_id: 2,
    job_title: "Data Analyst",
    applicant_name: "Jane Smith",
    application_date: "2024-09-02",
    application_status: "approved",
    action: "View",
  },
  {
    job_application_id: 3,
    job_title: "Project Manager",
    applicant_name: "Alice Johnson",
    application_date: "2024-09-03",
    application_status: "rejected",
    action: "View",
  },
  {
    job_application_id: 4,
    job_title: "UX Designer",
    applicant_name: "Bob Brown",
    application_date: "2024-09-04",
    application_status: "pending",
    action: "View",
  },
  {
    job_application_id: 5,
    job_title: "Marketing Specialist",
    applicant_name: "Mary Davis",
    application_date: "2024-09-05",
    application_status: "pending",
    action: "View",
  },
  {
    job_application_id: 6,
    job_title: "HR Manager",
    applicant_name: "Charlie Wilson",
    application_date: "2024-09-06",
    application_status: "approved",
    action: "View",
  },
  {
    job_application_id: 7,
    job_title: "Sales Executive",
    applicant_name: "Diana Miller",
    application_date: "2024-09-07",
    application_status: "rejected",
    action: "View",
  },
  {
    job_application_id: 8,
    job_title: "Customer Support",
    applicant_name: "Evan Moore",
    application_date: "2024-09-08",
    application_status: "pending",
    action: "View",
  },
  {
    job_application_id: 9,
    job_title: "Business Analyst",
    applicant_name: "Olivia Taylor",
    application_date: "2024-09-09",
    application_status: "approved",
    action: "View",
  },
  {
    job_application_id: 10,
    job_title: "IT Consultant",
    applicant_name: "Nathan Harris",
    application_date: "2024-09-10",
    application_status: "pending",
    action: "View",
  },
  {
    job_application_id: 11,
    job_title: "Accountant",
    applicant_name: "Zoe Clark",
    application_date: "2024-09-11",
    application_status: "rejected",
    action: "View",
  },
  {
    job_application_id: 12,
    job_title: "Legal Advisor",
    applicant_name: "Henry Lee",
    application_date: "2024-09-12",
    application_status: "pending",
    action: "View",
  },
  {
    job_application_id: 13,
    job_title: "Operations Manager",
    applicant_name: "Isabella Scott",
    application_date: "2024-09-13",
    application_status: "approved",
    action: "View",
  },
  {
    job_application_id: 14,
    job_title: "Research Analyst",
    applicant_name: "Liam King",
    application_date: "2024-09-14",
    application_status: "pending",
    action: "View",
  },
  {
    job_application_id: 15,
    job_title: "Product Manager",
    applicant_name: "Sophie Lewis",
    application_date: "2024-09-15",
    application_status: "rejected",
    action: "View",
  },
  {
    job_application_id: 16,
    job_title: "Front-End Developer",
    applicant_name: "Lucas Young",
    application_date: "2024-09-16",
    application_status: "pending",
    action: "View",
  },
  {
    job_application_id: 17,
    job_title: "Back-End Developer",
    applicant_name: "Emily Hall",
    application_date: "2024-09-17",
    application_status: "approved",
    action: "View",
  },
  {
    job_application_id: 18,
    job_title: "Network Engineer",
    applicant_name: "Mason Wright",
    application_date: "2024-09-18",
    application_status: "pending",
    action: "View",
  },
  {
    job_application_id: 19,
    job_title: "QA Tester",
    applicant_name: "Harper Allen",
    application_date: "2024-09-19",
    application_status: "rejected",
    action: "View",
  },
  {
    job_application_id: 20,
    job_title: "DevOps Engineer",
    applicant_name: "Daniel Lopez",
    application_date: "2024-09-20",
    application_status: "pending",
    action: "View",
  },
];
